# This is the base for generated parameter sweep configurations
# Compared to v1, this now has variable update interval and higher max_speed

# -- FIXED PARAMETERS ----------------------------------------------------------

world_grid_width: 384
world_grid_height: 384

data_dir_base: '/media/woodlab/DATAPART1/jtebert/grid-decisions-data/hybrid-algorithm2/woodlab-pre_decision_sweep'

start_trial: 1
num_trials: 50
max_trial_duration: 5000
img_dir: "imgs"

# THESE ARE PLACEHOLDERS; THEY AREN'T USED OR TUNED FOR THIS STAGE
# Boids parameters (only in hybrid movement)
lj_a: 6 # Lennard-Jones potential
lj_b: 3 # Lennard-Jones potential
lj_epsilon: 1
lj_gamma: 1
boids_step_interval: 10
rx_table_timeout: 512
post_decision_movement: "flock"

# max_speed: 25

# -- FOR PSO ONLY --------------------------------------------------------------

end_condition: 'first_find'
end_val: 4
movement_type: 'hybrid'
target_val: 4 # Same as value-based end val, so that time-based ending condition knows it

# -- FIXED TEST_PARAMETERS -----------------------------------------------------

# NOTE: This is now used as the UPPER BOUND for the update interval
# The actual update interval is: min(pso_step_interval, t-t^P, t-t^G)
pso_step_interval: 128
# Flag for whether to use pso_step interval as constant (default) or in above func.
is_pso_step_interval_constant: false

# -- VARIED PARAMETERS ---------------------------------------------------------

vary_params:
- env_octaves
- num_robots
- comm_range
- max_speed
- gradient_weight
- pso_inertia
- pso_weights

env_octaves: [1, 3, 5]
num_robots: [8, 16, 32]
comm_range: [4, 8, 16, 32, 800] # 800 is global communication since it's bigger than the grid
max_speed: [2, 25]
gradient_weight: [0, 4, 8, 16, 64]
pso_inertia: [0, 0.5, 1.0, 10.0]
pso_weights: [0, 0.01, 0.025, 0.05, 0.1, 1]
